// <auto-generated />
using EnviGerenciator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EnvioGerenciator.Migrations
{
    [DbContext(typeof(ObjetoContext))]
    [Migration("20250216030934_Relação filial Remessas")]
    partial class RelaçãofilialRemessas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnviGerenciator.Model.Filial", b =>
                {
                    b.Property<int>("FilialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilialId"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("FilialId");

                    b.ToTable("filiais");
                });

            modelBuilder.Entity("EnviGerenciator.Model.Objeto", b =>
                {
                    b.Property<int>("ObjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjetoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Patrimonio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RemessaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ObjetoId");

                    b.HasIndex("RemessaId");

                    b.ToTable("objetos");
                });

            modelBuilder.Entity("EnviGerenciator.Model.Remessa", b =>
                {
                    b.Property<int>("RemessaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemessaId"));

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("RemessaId");

                    b.HasIndex("FilialId");

                    b.ToTable("remessas");
                });

            modelBuilder.Entity("EnviGerenciator.Model.Objeto", b =>
                {
                    b.HasOne("EnviGerenciator.Model.Remessa", "Remessa")
                        .WithMany("Objetos")
                        .HasForeignKey("RemessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remessa");
                });

            modelBuilder.Entity("EnviGerenciator.Model.Remessa", b =>
                {
                    b.HasOne("EnviGerenciator.Model.Filial", "Filial")
                        .WithMany("Remessas")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("EnviGerenciator.Model.Filial", b =>
                {
                    b.Navigation("Remessas");
                });

            modelBuilder.Entity("EnviGerenciator.Model.Remessa", b =>
                {
                    b.Navigation("Objetos");
                });
#pragma warning restore 612, 618
        }
    }
}
